# Generated by Django 3.2.11 on 2022-03-29 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='course',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='year',
            field=models.CharField(blank=True, choices=[('1', 'I will make mom proud'), ('2', 'wtf is this shit?'), ('3', 'will i die a virgin?'), ('4', 'bro why am i still here')], max_length=1),
        ),
    ]
